### PR TITLE
Fix the issue of failed outlier configuration queries

### LINKED ISSUE #1543: Fix Configuration Management function test problems
### What happened?

The configuration management function test is faulty

### How can we reproduce it (as minimally and precisely as possible)?

The problem can be reproduced when the latest backend code is used to add, modify, and query configurations.

### Anything else we need to know?

nothing

### Sermant version

<details>
1.4.1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by hanbingleixue**
**What type of PR is this?**

Bug

**What this PR does / why we need it?**

1、Fixed an issue where the outlier plug-in configuration fails to be queried.
2、Fix the issue that the prompt message on the page is in English.
3、Fix the problem of group display in KIE.

**Which issue(s) this PR fixes？**

Fixes #1543 

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [x] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigView.vue [hunk 1]
```diff
@@ -274,6 +274,19 @@ const fillServiceNames = () => {
...
+  ['02', '配置查询失败'],
+  ['03', '配置已存在'],
+  ['04', '新增配置失败'],
+  ['05', '发布配置失败'],
+  ['06', '删除配置失败'],
+  ['07', '配置不存在'],
+  ['08', '缺少请求参数'],
+  ['09', '请求失败'],
+]);
+
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/views/ConfigView.vue]: extract this to common place for multiple usage

Comment (hanbingleixue) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigView.vue]: done

**Review by daizhenyu — APPROVED** [review]

**Review by lilai23 — APPROVED** [review]
