### PR TITLE
fixed the traffic label is lost in the HikariDataSource scenario

### LINKED ISSUE #1718: The traffic label is lost in the HikariDataSource scenario.
### What happened?

The traffic label is lost in the HikariDataSource scenario

### How can we reproduce it (as minimally and precisely as possible)?

Fix in cross-thread label passing.

### Anything else we need to know?

_No response_

### Sermant version

2.x

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by chengyouling**
**What type of PR is this?**

Bug.

**What this PR does / why we need it?**

The traffic label is lost in the HikariDataSource scenario.

**Which issue(s) this PR fixes？**

Fixes #1718

**Does this PR introduce a user-facing change?**

No

## Checklist
- [ ] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [ ] Make sure you have squashed your change to one single commit.
- [ ] GitHub Actions works fine in this PR.

### CODE REVIEW

**Review by provenceee — DISMISSED** [review]

File: sermant-plugins/sermant-router/router-transmit-plugin/src/main/java/io/sermant/router/transmit/wrapper/AbstractThreadWrapper.java [hunk 1]
```diff
@@ -117,6 +120,9 @@ private void before(Object obj) {
     }
 
     private void after() {
```
Comment (lilai23) [inline sermant-plugins/sermant-router/router-transmit-plugin/src/main/java/io/sermant/router/transmit/wrapper/AbstractThreadWrapper.java:125]: directly return in before method

Comment (chengyouling) [reply sermant-plugins/sermant-router/router-transmit-plugin/src/main/java/io/sermant/router/transmit/wrapper/AbstractThreadWrapper.java:125]: fixed

**Review by provenceee — APPROVED** [review]

**Review by lilai23 — APPROVED** [review]
