### PR TITLE
Fixed the issue that new configurations fail to be verified

### LINKED ISSUE #1543: Fix Configuration Management function test problems
### What happened?

The configuration management function test is faulty

### How can we reproduce it (as minimally and precisely as possible)?

The problem can be reproduced when the latest backend code is used to add, modify, and query configurations.

### Anything else we need to know?

nothing

### Sermant version

<details>
1.4.1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by hanbingleixue**
**What type of PR is this?**

Bug

**What this PR does / why we need it?**

1、Fixed the issue that new configurations fail to be verified
2、Fixes an issue where required boxes were missing flags
3、Fix the issue that the prompt message on the page is in English.

**Which issue(s) this PR fixes？**

Fixes #1543 

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [x] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
                   style="width: 90%;margin-right: 5px;" :disabled="types.modifyFlay" @change="changePluginType()"
                   v-if="types.modifyFlay">
           <template #prepend>
-            <span color="#606266">插件类型</span>
+            <span color="#606266" style="width: 100px;text-align: center;">插件类型</span>
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: better use class instead of style

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue [hunk 2]
```diff
@@ -161,20 +161,38 @@
...
+                    style="width: 90%;margin-right: 5px;" :disabled="types.modifyFlay" @change="handlerChange(false)">
+            <template #prepend>
+              <span color="#606266" style="width: 100px;text-align: center;">service</span>
+            </template>
+          </el-input>
+          <el-tooltip class="box-item" effect="dark"
+                      content="微服务的名称，由微服务配置文件的dubbo.application.name、spring.applicaton.name确定"
+                      placement="right-start">
+            <el-icon color="lightgray" size="20">
+              <Warning/>
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: info

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue [hunk 3]
```diff
@@ -161,20 +161,38 @@
...
+            </el-icon>
+          </el-tooltip>
+        </el-form-item>
+        <el-form-item v-if="requestParam.pluginType != 'flowcontrol'">
           <el-input size="large" v-model.trim="requestParam.serviceName" placeholder="请输入服务名称，为空时下发全局配置"
-                    style="width: 90%;margin-right: 5px;" :disabled="types.modifyFlay" @change="handlerChange(false)" v-if="requestParam.pluginType == 'router'">
+                    style="width: 90%;margin-right: 5px;" :disabled="types.modifyFlay" @change="handlerChange(false)"
+                    v-if="requestParam.pluginType == 'router'">
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: put 'v-if' in front

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue [hunk 4]
```diff
@@ -161,20 +161,38 @@
...
         </el-descriptions>
-        <el-form-item prop="serviceName">
+        <el-form-item prop="serviceName" v-if="requestParam.pluginType == 'flowcontrol'">
+          <el-input size="large" v-model.trim="requestParam.serviceName" placeholder="请输入服务名称"
+                    style="width: 90%;margin-right: 5px;" :disabled="types.modifyFlay" @change="handlerChange(false)">
+            <template #prepend>
+              <span color="#606266" style="width: 100px;text-align: center;">service</span>
+            </template>
+          </el-input>
+          <el-tooltip class="box-item" effect="dark"
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: tooltip can ba a common component which just have different content

Comment (hanbingleixue) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: done

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue (hunk 1 above)
Comment (hanbingleixue) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: done

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue (hunk 2 above)
Comment (hanbingleixue) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: Waring is an icon, there is no info icon.

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue (hunk 3 above)
Comment (hanbingleixue) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: done

File: sermant-backend/src/main/webapp/frontend/src/components/layouts/TooltipIcon.vue [hunk 5]
```diff
@@ -0,0 +1,24 @@
+<template>
+  <el-tooltip class="box-item" effect="dark" :content="content" placement="right-start">
+    <el-icon color="lightgray" size="20">
+      <Warning/>
```
Comment (lilai23) [inline sermant-backend/src/main/webapp/frontend/src/components/layouts/TooltipIcon.vue:4]: information，not  warning

File: sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue (hunk 2 above)
Comment (lilai23) [reply sermant-backend/src/main/webapp/frontend/src/views/ConfigInfo.vue]: use question `?`

**Review by lilai23 — APPROVED** [review]

**Review by daizhenyu — APPROVED** [review]
