### PR TITLE
Fix the issue that a NullPointerException occurs when initialize the unified configuration

### LINKED ISSUE #1591: ConfigManager#initialize phase, log warnings/errors, causing agent mount fail
### What happened?

i add myList property in config.properties and AgentConfig, and default it is empty string.
```properties
agent.config.myList=
```
when io.sermant.core.config.utils.ConfigValueUtil#parseConfigToCollection, parse empty string, then log warn.
image
it cause new LogEventCollector instance created, but Config is not ready, so it cause NPE, and agent mount fail.
image

### How can we reproduce it (as minimally and precisely as possible)?

you can try set agent.config.serviceInjectList as empty string.

### Anything else we need to know?

_No response_

### Sermant version

2.0.0

### OS version

MacOS14.1

### PR DESCRIPTION
**Pull request by hanbingleixue**
**What type of PR is this?**

Bug

**What this PR does / why we need it?**

Fix the issue that a NullPointerException occurs when the configuration item type is set and the configuration content is empty during configuration initialization parsing.  When the configuration type of a configuration item is collection and the configuration content is empty, an warning log is recorded. The LogEventCollector collects and reports warning logs. However, the event configuration is not initialized, so a NullPointerException is thrown on event collection

**Which issue(s) this PR fixes？**

Fixes #1591 

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [ ] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java [hunk 1]
```diff
@@ -41,7 +41,7 @@ public class EventCollector {
     // the queue is full, event is reported automatically
     private final BlockingQueue<Event> eventQueue = new ArrayBlockingQueue<>(100);
 
-    private final EventConfig eventConfig = ConfigManager.getConfig(EventConfig.class);
+    private EventConfig eventConfig = ConfigManager.getConfig(EventConfig.class);
```
Comment (daizhenyu) [inline sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: Change private to protected so that subclasses can use it.

Comment (hanbingleixue) [reply sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: done

File: sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java [hunk 2]
```diff
@@ -119,11 +125,26 @@ private boolean checkEventInfoOfferInterval(EventInfo eventInfo) {
      * Periodically clear the event reporting time cache
      */
     protected void cleanOfferTimeCacheMap() {
+        if (!isEnableEvent()) {
+            return;
+        }
```
Comment (lilai23) [inline sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: no need to check

File: sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java [hunk 3]
```diff
@@ -108,6 +111,9 @@ private void sendEventInitiative() {
      * @return boolean result
      */
     private boolean checkEventInfoOfferInterval(EventInfo eventInfo) {
+        if (!isEnableEvent()) {
+            return false;
+        }
```
Comment (lilai23) [inline sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: no need to check

Comment (hanbingleixue) [reply sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: done

File: sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java (hunk 2 above)
Comment (hanbingleixue) [reply sermant-agentcore/sermant-agentcore-core/src/main/java/io/sermant/core/event/EventCollector.java]: done

**Review by daizhenyu — APPROVED** [review]

**Review by lilai23 — APPROVED** [review]
