### PR TITLE
【fix】fix bug for okhttpclient(state error), throw method exception then error

### LINKED ISSUE #835: 【bug】fix the registry plugin bugs
### What happened?

can not work

### How can we reproduce it (as minimally and precisely as possible)?

no

### Anything else we need to know?

_No response_

### Sermant version

<details>
0.6.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by justforstudy-A**
What type of PR is this?

/bug

Which issue(s) this PR fixes:

Fixes #835

Use case description: fix registry plugin bugs

Does this PR introduce a user-facing change?

No

Additional documentation e.g., usage docs, etc.:

No

### CODE REVIEW

File: sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java [hunk 1]
```diff
@@ -71,14 +74,29 @@ protected ExecuteContext doBefore(ExecuteContext context) throws Exception {
...
+        invoke.ifPresent(o -> setResultOrThrow(context, o, uri.getPath()));
         return context;
     }
 
+    private void setResultOrThrow(ExecuteContext context, Object result, String url) {
+        if (result instanceof IOException) {
+            LOGGER.log(Level.SEVERE, "Ok http client request error, uri is " + url, (Exception) result);
+            context.setThrowableOut((Exception) result);
+        }
+        context.skip(result);
```
Comment (luanwenfei-venus) [inline sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java]: 抛出异常还需要返回结果吗？

**Review by luanwenfei-venus — DISMISSED** [review]

File: sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java (hunk 1 above)
Comment (justforstudy-A) [reply sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java]: 已修改

**Review by xuezechao1 — APPROVED** [review]

**Review by luanwenfei-venus — APPROVED** [review]

**Review by robotLJW — APPROVED** [review]
lgtm
