### PR TITLE
【fix】fix bug for springboot registry plugin

### LINKED ISSUE #959: 【fix】fix bug for springboot registry plugin
### What happened?

if the url which for springboot registry plugin is invalid, it will throw ex

### How can we reproduce it (as minimally and precisely as possible)?

use url request whose url is invalid, such as http://www.domain.com/test

### Anything else we need to know?

_No response_

### Sermant version

<details>
0.7.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by justforstudy-A**
What type of PR is this?

/feat

Which issue(s) this PR fixes:

Fixes #959 

Use case description: 
1.fix the problem that it will throw ex when url is invalid but domain is satisfied
2.optimize the logic for checking host by reducing the extra operation to resolve hostAndPath

Does this PR introduce a user-facing change?

No

Additional documentation e.g., usage docs, etc.:

No

### CODE REVIEW

File: sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java [hunk 1]
```diff
@@ -64,9 +64,11 @@ protected ExecuteContext doBefore(ExecuteContext context) throws Exception {
         }
         Request request = rawRequest.get();
         URI uri = request.url().uri();
+        if (!PlugEffectWhiteBlackUtils.isHostEqualRealmName(uri.getHost())) {
+            return context;
+        }
         Map<String, String> hostAndPath = RequestInterceptorUtils.recoverHostAndPath(uri.getPath());
-        if (!PlugEffectWhiteBlackUtils.isAllowRun(uri.getHost(), hostAndPath.get(HttpConstants.HTTP_URI_HOST),
```
Comment (lilai23) [inline sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java:68]: isAllowRun方法重写或删除掉，不再需要PlugEffectWhiteBlackUtils.isUrlContainsRealmName判断域名

**Review by lilai23 — APPROVED** [review]

**Review by robotLJW — APPROVED** [review]
/lgtm
