### PR TITLE
fix: store heartbeat use redis setex with wrong timeunit

### LINKED ISSUE #1610: store heartbeat use redis setex with wrong timeunit
### What happened?

max.effective.time=60000, the time unit is milliseconds.
image
when store heartbeat use redis setex command, directly set ttl as 60000 seconds.
image

### How can we reproduce it (as minimally and precisely as possible)?

just start an agent to send heartbeat.

### Anything else we need to know?

_No response_

### Sermant version

2.0.0

### OS version

MacOS 14.1

### PR DESCRIPTION
**Pull request by AYue-94**
fix #1610

### CODE REVIEW

File: sermant-backend/src/main/java/io/sermant/backend/dao/redis/RedisClientImpl.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public boolean addEvent(Event event) {
 
     @Override
     public boolean addInstanceMeta(InstanceMeta instanceMeta) {
-        redisOperation.setex(instanceMeta.getMetaHash(), backendConfig.getHeartbeatEffectiveTime(),
+        redisOperation.setex(instanceMeta.getMetaHash(), backendConfig.getHeartbeatEffectiveTime() / 1000,
```
Comment (hanbingleixue) [inline sermant-backend/src/main/java/io/sermant/backend/dao/redis/RedisClientImpl.java]: You are advised to add the psetex method to the RedisOperation interface to set the expiration time in milliseconds. Use the jedis.psetex or jedisCluster.psetex method to implement the method.

Comment (AYue-94) [reply sermant-backend/src/main/java/io/sermant/backend/dao/redis/RedisClientImpl.java]: I add psetex method in RedisOperation, PTAL

**Review by lilai23 — APPROVED** [review]

**Review by hanbingleixue — APPROVED** [review]
