### PR TITLE
Fix the issue that ClassCastException error is reported with xDS Router

### LINKED ISSUE #1635: The ClassCastException Error Is Reported When the RestTemplate Uses xDS Routing
### What happened?

The ClassCastException Error Is Reported When the RestTemplate Uses xDS Routing:
java.lang.ClassCastException: org.springframework.cloud.client.DefaultServiceInstance cannot be cast to com.netflix.loadbalancer.Server

### How can we reproduce it (as minimally and precisely as possible)?

When the RestTemplate Uses xDS Routing to call down stream.

### Anything else we need to know?

_No response_

### Sermant version

2.1.0

### OS version

_No response_

### PR DESCRIPTION
**Pull request by daizhenyu**
**What type of PR is this?**

Bug.

**What this PR does / why we need it?**

Fix the issue that ClassCastException error is reported when the RestTemplate uses xDS routing.

**Which issue(s) this PR fixes？**

Fixes #1635

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [ ] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-plugins/sermant-router/spring-router-plugin/src/main/java/io/sermant/router/spring/utils/SpringRouterUtils.java [hunk 1]
```diff
@@ -103,4 +118,10 @@ private static org.springframework.cloud.client.ServiceInstance convertServiceIn
                 instanceIdBuilder.toString(), xdsServiceInstance.getServiceName(), xdsServiceInstance.getHost(),
                 xdsServiceInstance.getPort(), routerConfig.isEnabledSpringCloudXdsRouteSecure());
     }
+
+    private static Server convertServiceInstance2Server(
+            io.sermant.core.service.xds.entity.ServiceInstance xdsServiceInstance) {
```
Comment (lilai23) [inline sermant-plugins/sermant-router/spring-router-plugin/src/main/java/io/sermant/router/spring/utils/SpringRouterUtils.java]: no need to use full name

Comment (daizhenyu) [reply sermant-plugins/sermant-router/spring-router-plugin/src/main/java/io/sermant/router/spring/utils/SpringRouterUtils.java]: done

**Review by hanbingleixue — APPROVED** [review]

**Review by lilai23 — APPROVED** [review]
