### PR TITLE
fix issue of plugin config reload dynamically failure

### LINKED ISSUE #1520: fail to load plugin config dynamically at the second time
### What happened?

After dynamically installing a plugin and unstalling it, try to install the plugin again then throws ClassCastException
`2024-05-22 16:10:37.191 [ERROR] [io.sermant.core.plugin.service.PluginServiceManager] [initPluginServices:59] [Attach Listener] Error occurs while starting plugin service: class io.sermant.monitor.service.report.MetricServiceImpl
java.lang.ClassCastException: io.sermant.monitor.config.MonitorServiceConfig cannot be cast to io.sermant.monitor.config.MonitorServiceConfig
	at io.sermant.monitor.service.report.MetricServiceImpl.start(MetricServiceImpl.java:45)
	at io.sermant.core.plugin.service.PluginServiceManager.initPluginServices(PluginServiceManager.java:56)
	at io.sermant.core.plugin.PluginManager.doInitPlugin(PluginManager.java:203)
	at io.sermant.core.plugin.PluginManager.executeInit(PluginManager.java:188)
	at io.sermant.core.plugin.PluginManager.initPlugins(PluginManager.java:175)
	at io.sermant.core.plugin.PluginManager.install(PluginManager.java:81)
	at io.sermant.core.command.PluginsInstallCommandExecutor.execute(PluginsInstallCommandExecutor.java:44)
	at io.sermant.core.command.CommandProcessor.process(CommandProcessor.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.sermant.premain.AgentLauncher.executeCommand(AgentLauncher.java:153)
	at io.sermant.premain.AgentLauncher.launchAgent(AgentLauncher.java:93)
	at io.sermant.premain.AgentLauncher.agentmain(AgentLauncher.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)`

### How can we reproduce it (as minimally and precisely as possible)?

when dynamically install a plugin at the second time, you can reproduce it

### Sermant version

1.4.0 / develop branch

### PR DESCRIPTION
**Pull request by lilai23**
**What type of PR is this?**

Bug

**What this PR does / why we need it?**

Add a custom yaml constructor for snakeyaml to make the same plugin config string can be loaded by new pluginclassloader rather than old pluginclassloader when install a plugin at the second time

**Which issue(s) this PR fixes？**

Fixes #1520

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [x] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/config/SermantYamlConstructor.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    /**
+     * constructor
+     */
+    public SermantYamlConstructor() {
+        super(Object.class, new LoaderOptions());
+        loader = Thread.currentThread().getContextClassLoader();
+    }
+
+    /**
+     * Load class with specific class
```
Comment (daizhenyu) [inline sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/config/SermantYamlConstructor.java]: with specific classloader?

Comment (lilai23) [reply sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/config/SermantYamlConstructor.java]: resolved

**Review by hanbingleixue — APPROVED** [review]

**Review by daizhenyu — APPROVED** [review]
