### PR TITLE
Fix some bugs in xds flow control

### LINKED ISSUE #1742: Fix the issue with the xDS flow control functionality integration test
### What happened?

1. Added support for Okhttp2 2.2.0.
2. The number of retry times is incorrect because the response header of HttpUrlConnection is not updated.
3. The flow control configuration cannot obtain the millisecond-level time.
4. Some retry conditions are inconsistent with Istio.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use Okhttp2 2.2.0 to test the flow control function. The problem can be reproduced.
2. When HttpUrlConnection is used to retry with a specified response header, the response header obtained after the retry is still the first response header, and the retry times are reached.
3. The flow control function does not take effect when the time in the flow control matching configuration is set to ms.
4. Retry conditions for link errors are configured. Retry is performed when the request times out.

### Anything else we need to know?

_No response_

### Sermant version

<details>
2.2.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by hanbingleixue**
**What type of PR is this?**

Bug

**What this PR does / why we need it?**

Fix some bugs in xds flow control

How can we reproduce it (as minimally and preci

**Which issue(s) this PR fixes？**

Fixes #1742 

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [ ] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java [hunk 1]
```diff
@@ -139,11 +140,20 @@ private static XdsInstanceCircuitBreakers parseInstanceCircuitBreakers(Cluster c
...
-        long ejectionTime = java.time.Duration.ofSeconds(outlierDetection.getBaseEjectionTime().getSeconds())
-                .toMillis();
-        xdsInstanceCircuitBreakers.setBaseEjectionTime(ejectionTime);
+        long interval = outlierDetection.getInterval().getSeconds();
+        if (interval != 0) {
+            xdsInstanceCircuitBreakers.setInterval(Duration.ofSeconds(interval).toMillis());
+        } else {
+            interval = Duration.ofNanos(outlierDetection.getInterval().getNanos()).toMillis();
+            xdsInstanceCircuitBreakers.setInterval(interval);
+        }
```
Comment (daizhenyu) [inline sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java]: Extract as a method, the same as below

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ConnectErrorRetryCondition.java [hunk 2]
```diff
@@ -51,8 +50,9 @@ public boolean needRetry(Retry retry, Throwable ex, String statusCode, Object re
     }
 
     private boolean isConnectErrorException(Throwable ex) {
-        if (ex instanceof InterruptedIOException && StringUtils.contains(ex.getMessage(), "timeout")) {
-            return true;
+        if ((ex instanceof SocketTimeoutException || ex instanceof TimeoutException)
```
Comment (daizhenyu) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ConnectErrorRetryCondition.java]: isRequestTimeOutExeception()

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java [hunk 3]
```diff
@@ -34,18 +36,25 @@
 public class ResetErrorCondition implements RetryCondition {
     @Override
     public boolean needRetry(Retry retry, Throwable ex, String statusCode, Object result) {
```
Comment (daizhenyu) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java]: isNeedRetry

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java [hunk 4]
```diff
@@ -34,18 +36,25 @@
...
             }
         }
-        if (realException instanceof SocketTimeoutException && !StringUtils.isEmpty(ex.getMessage())
-                && realException.getMessage().contains("Read timed out")) {
+        String message = realException.getMessage();
+        if (StringUtils.isEmpty(message)) {
+            return false;
+        }
+        if ((ex instanceof SocketTimeoutException || ex instanceof TimeoutException)
+                && message.contains("Read timed out")) {
```
Comment (daizhenyu) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java]: Extract as a method

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
+/*
+ * Copyright (C) 2024-2024 Sermant Authors. All rights reserved.
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: 2025

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+     */
+    public static Optional<RetryCondition> getRetryConditionByName(String conditionName) {
+        for (ExceptionRetryConditionType retryConditionType : ExceptionRetryConditionType.values()) {
+            if (StringUtils.equals(retryConditionType.getConditionName(), conditionName)) {
+                return Optional.of(retryConditionType.getRetryCondition());
+            }
+        }
+        return Optional.empty();
+    }
+}
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: Use EnumMap with key：conditionName and value：RetryCondition and initail it in statics block. The efficiency is better

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java [hunk 7]
```diff
@@ -105,7 +87,7 @@ public RetryCondition getRetryCondition() {
      * @return instance of implements class for retry condition
      */
     public static Optional<RetryCondition> getRetryConditionByName(String conditionName) {
-        for (RetryConditionType retryConditionType : RetryConditionType.values()) {
+        for (ResultRetryConditionType retryConditionType : ResultRetryConditionType.values()) {
             if (StringUtils.equals(retryConditionType.getConditionName(), conditionName)) {
                 return Optional.of(retryConditionType.getRetryCondition());
             }
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java]: same above

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ServerExceptionCondition.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
+/*
+ * Copyright (C) 2024-2024 Sermant Authors. All rights reserved.
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ServerExceptionCondition.java]: 2025

File: sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java [hunk 9]
```diff
@@ -139,16 +140,21 @@ private static XdsInstanceCircuitBreakers parseInstanceCircuitBreakers(Cluster c
...
     }
+
+    private static long getDurationInMillis(com.google.protobuf.Duration duration) {
+        long interval = duration.getSeconds();
+        if (interval != 0) {
+            return Duration.ofSeconds(interval).toMillis();
+        }
+        return Duration.ofNanos(duration.getNanos()).toMillis();
+    }
 }
```
Comment (lilai23) [inline sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java]: seconds add nanos. Extract this method

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+
+    /**
+     * The type of conditional judgment for connect errors
+     */
+    CONNECT_ERROR("connect-failure", new ConnectErrorRetryCondition()),
+
+    /**
+     * The type of conditional judgment for Specify response headers
+     */
+    SPECIFIC_HEADER_NAME_ERROR("retriable-headers", new SpecificHeaderNameErrorRetryCondition());
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: it is better to make the type name and class name same as condition name

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java [hunk 11]
```diff
@@ -34,7 +31,7 @@
  * @author zhp
  * @since 2024-11-29
  */
-public enum RetryConditionType {
+public enum ResultRetryConditionType {
     /**
```
Comment (lilai23) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java]: merge ResultRetryConditionType  with ExceptionRetryConditionType，and add a filed to distinguish retry on status code or exception

Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java (hunk 10 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: done

File: sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java (hunk 9 above)
Comment (hanbingleixue) [reply sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ServerExceptionCondition.java (hunk 8 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ServerExceptionCondition.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java (hunk 7 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ResultRetryConditionType.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java (hunk 6 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java (hunk 5 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/ExceptionRetryConditionType.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java (hunk 4 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java (hunk 3 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ResetErrorCondition.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ConnectErrorRetryCondition.java (hunk 2 above)
Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/condition/ConnectErrorRetryCondition.java]: done

File: sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java (hunk 1 above)
Comment (hanbingleixue) [reply sermant-agentcore/sermant-agentcore-implement/src/main/java/io/sermant/implement/service/xds/utils/CdsProtocolTransformer.java]: done

File: sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/RetryConditionType.java [hunk 12]
```diff
@@ -38,42 +39,45 @@ public enum RetryConditionType {
     /**
      * The type of conditional judgment for server errors
      */
-    SERVER_ERROR("5xx", new ServerErrorCondition()),
+    SERVER_ERROR("5xx", new ServerErrorRetryCondition(), 2),
```
Comment (daizhenyu) [inline sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/RetryConditionType.java:45]: use constant

Comment (hanbingleixue) [reply sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/io/sermant/flowcontrol/common/xds/retry/RetryConditionType.java:45]: done

**Review by lilai23 — APPROVED** [review]

**Review by daizhenyu — APPROVED** [review]
