### PR TITLE
Add synchronization to fixed SQL92 expression build error problem

### LINKED ISSUE #1786: Add synchronization to fixed SQL92 expression build error problem
### What happened?

When the service is started, multiple threads operate the subscriptionData object at the same time. As a result, an incorrect SQL92 expression is generated when the SQL92 expression is constructed.

### How can we reproduce it (as minimally and precisely as possible)?

Add synchronization to fixed SQL92 expression build error problem.

### Anything else we need to know?

_No response_

### Sermant version

2.x

### OS version

_No response_

### PR DESCRIPTION
**Pull request by chengyouling**
**What type of PR is this?**

Bug.

**What this PR does / why we need it?**

Add synchronization to fixed SQL92 expression build error problem.

**Which issue(s) this PR fixes？**

Fixes #1786

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [x] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/interceptor/RocketMqSchedulerRebuildSubscriptionInterceptor.java [hunk 1]
```diff
@@ -47,35 +47,37 @@ public class RocketMqSchedulerRebuildSubscriptionInterceptor extends RocketMqAbs
...
-        }
-        List<Object> retryTopicSubscriptions = new ArrayList<>();
-        List<Object> originTopicSubscriptions = new ArrayList<>();
-        buildTopicSubscriptions(subscriptionInner, retryTopicSubscriptions, originTopicSubscriptions);
-        Object changedOriginSubscription = null;
-        for (Object subscriptionData : originTopicSubscriptions) {
-            if (RocketMqSubscriptionDataUtils
+        synchronized (RocketMqSchedulerRebuildSubscriptionInterceptor.class) {
+            ConcurrentMap<String, Object> subscriptionInner = (ConcurrentMap<String, Object>) context.getResult();
+            RebalanceImpl balance = (RebalanceImpl) context.getObject();
```
Comment (lilai23) [inline sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/interceptor/RocketMqSchedulerRebuildSubscriptionInterceptor.java]: balance -> rebalance

Comment (chengyouling) [reply sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/interceptor/RocketMqSchedulerRebuildSubscriptionInterceptor.java]: fixed

**Review by lilai23 — APPROVED** [review]

**Review by provenceee — APPROVED** [review]
