### PR TITLE
fixed when consumerGroupTag contains uppercase characters, the gray flag cannot be matched problem

### LINKED ISSUE #1782: When consumerGroupTag contains uppercase characters, the gray flag cannot be matched
### What happened?

When consumerGroupTag contains uppercase characters, the gray flag cannot be matched.

### How can we reproduce it (as minimally and precisely as possible)?

Adjust the regular expression verification for matching consumerGroupTag.

### Anything else we need to know?

_No response_

### Sermant version

2.x

### PR DESCRIPTION
**Pull request by chengyouling**
**What type of PR is this?**

Bug.

**What this PR does / why we need it?**

When consumerGroupTag contains uppercase characters, the gray flag cannot be matched.

**Which issue(s) this PR fixes？**

Fixes #1782

**Does this PR introduce a user-facing change?**

No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/sermant-io/Sermant/issues) related with this PR before you start working on it.
- [x] Make sure you have squashed your change to one single commit.
- [x] GitHub Actions works fine in this PR.

### CODE REVIEW

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java [hunk 1]
```diff
@@ -72,7 +76,16 @@ public static String getGrayGroupTag() {
...
         Optional<GrayTagItem> itemOptional
                 = MqGrayConfigCache.getCacheConfig().getMatchedGrayTagByServiceMeta(MICRO_SERVICE_PROPERTIES);
-        return itemOptional.map(grayTagItem -> standardFormatGroupTag(grayTagItem.getConsumerGroupTag())).orElse("");
+        if (itemOptional.isPresent()) {
+            String consumerGroup = itemOptional.get().getConsumerGroupTag();
+            if (PATTERN.matcher(consumerGroup).matches()) {
+                return itemOptional.get().getConsumerGroupTag();
+            } else {
+                LOGGER.warning(String.format(Locale.ENGLISH, "current consumerGroup tag [%s] not matches pattern "
+                        + "[a-zA-Z0-9_-], modify it and restart service to valid.", consumerGroup));
```
Comment (lilai23) [inline sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java]: "current consumerGroup tag [%s] does not match the required pattern [a-zA-Z0-9_-]. Please modify it to conform to this pattern and restart the service."

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java [hunk 2]
```diff
@@ -72,7 +76,16 @@ public static String getGrayGroupTag() {
         }
         Optional<GrayTagItem> itemOptional
                 = MqGrayConfigCache.getCacheConfig().getMatchedGrayTagByServiceMeta(MICRO_SERVICE_PROPERTIES);
-        return itemOptional.map(grayTagItem -> standardFormatGroupTag(grayTagItem.getConsumerGroupTag())).orElse("");
+        if (itemOptional.isPresent()) {
+            String consumerGroup = itemOptional.get().getConsumerGroupTag();
+            if (PATTERN.matcher(consumerGroup).matches()) {
+                return itemOptional.get().getConsumerGroupTag();
```
Comment (lilai23) [inline sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java]: itemOptional.get() can be define as a variable

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/test/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtilsTest.java [hunk 3]
```diff
@@ -45,11 +45,6 @@ public void testGetAutoCheckDelayTime() {
         Assert.assertSame(RocketMqGrayscaleConfigUtils.getAutoCheckDelayTime(), 15L);
     }
 
-    @Test
-    public void testStandardFormatGroupTag() {
-        Assert.assertEquals("gray-group", RocketMqGrayscaleConfigUtils.standardFormatGroupTag("grAY.Group"));
-    }
-
```
Comment (lilai23) [inline sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/test/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtilsTest.java:52]: add new test case

Comment (chengyouling) [reply sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/test/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtilsTest.java:52]: fixed

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java (hunk 2 above)
Comment (chengyouling) [reply sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java]: fixed

File: sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java (hunk 1 above)
Comment (chengyouling) [reply sermant-plugins/sermant-mq-grayscale/mq-grayscale-rocketmq-plugin/src/main/java/io/sermant/mq/grayscale/rocketmq/utils/RocketMqGrayscaleConfigUtils.java]: fixed

**Review by lilai23 — APPROVED** [review]

**Review by daizhenyu — APPROVED** [review]
